
export const EVENTS = {
    // Client → Server
    START_INTERVIEW: 'START_INTERVIEW',
    AUDIO_CHUNK: 'AUDIO_CHUNK',
    END_INTERVIEW: 'END_INTERVIEW',
    BARGE_IN: 'BARGE_IN',
    

    // Server → Client
    INTERVIEW_STARTED: 'INTERVIEW_STARTED',
    TRANSCRIPT_INTERIM: 'TRANSCRIPT_INTERIM',
    TRANSCRIPT_FINAL: 'TRANSCRIPT_FINAL',
    LLM_THINKING: 'LLM_THINKING',
    AUDIO_RESPONSE: 'AUDIO_RESPONSE',
    ERROR: 'ERROR',
    AI_MESSAGE: 'AI_MESSAGE',
    'INTERVIEW_ENDED': 'INTERVIEW_ENDED',
};